// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/registration": {
    params: {};
  };
  "/registration/result": {
    params: {};
  };
  "/verify": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/registration" | "/registration/result" | "/verify";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/registration.tsx": {
    id: "routes/registration";
    page: "/registration";
  };
  "routes/result.tsx": {
    id: "routes/result";
    page: "/registration/result";
  };
  "routes/capture.tsx": {
    id: "routes/capture";
    page: "/verify";
  };
};